# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340ff75acf7ba6ebe6740c602d39fdcd49c6abde01e0b3a3c4766045729aaea3fc46f02186434a134ac914dffce07b1e166b87d0bc0a02137babeb4d4128bf7b

test:
  secret_key_base: 840ae7dae17f8594ed07dc0ee7fa5ff2865e1b938d605fc5562a7d12969c8b52a3bebcd92fece2e14477a3b239c0d24d6ac29be9ce7d737b41c075f1e201978f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
